# Музыка
define music_waves = "audio/bg/waves.mp3"

# Игра
define sfx_alarm1 = "audio/sfx/alarm.ogg"
define sfx_alarm2 = "audio/sfx/alarm2.ogg"
define sfx_alarm3 = "audio/sfx/alarm3.ogg"
define sfx_cup_on_table = "audio/sfx/cup_on_table.ogg"
define sfx_electrisity1 = "audio/sfx/electrisity.ogg"
define sfx_electrisity2 = "audio/sfx/electrisity2.ogg"
define sfx_electrisity3 = "audio/sfx/electrisity3.ogg"
define sfx_evaporating_water = "audio/sfx/evaporating_water.wav"
define sfx_explosion = "audio/sfx/explosion.ogg"
define sfx_ballons = "audio/sfx/ballons.ogg"
define sfx_ballons2 = "audio/sfx/ballons2.wav"
define sfx_burning_fire = "audio/sfx/burning_fire.ogg"
define sfx_click2 = "audio/sfx/click2.wav"
define sfx_clicks = "audio/sfx/clicks.mp3"
define sfx_click_double = "audio/sfx/click_double.wav"
define sfx_click_first = "audio/sfx/click_first.wav"
define sfx_click_second = "audio/sfx/click_second.wav"
define sfx_cough_man = "audio/sfx/cough_man.ogg"
define sfx_door_open = "audio/sfx/door_open.ogg"
define sfx_light_on = "audio/sfx/light_on.mp3"
define sfx_fall_body = "audio/sfx/sfx_fall_body.wav"
define sfx_falling_objects = "audio/sfx/falling_objects.wav"
define sfx_fon_generator1 = "audio/sfx/fon_generator.ogg"
define sfx_fon_generator2 = "audio/sfx/fon_generator2.wav"
define sfx_fon_stremniy = "audio/sfx/fon_stremniy.ogg"
define sfx_glitch = "audio/sfx/glitch.ogg"
define sfx_heat_metal = "audio/sfx/heat_metal.ogg"
define sfx_laugh_men1 = "audio/sfx/heh_men.ogg"
define sfx_laugh_men2 = "audio/sfx/heh_victor.ogg"
define sfx_laugh_people = "audio/sfx/people_laughing.wav"
define sfx_laugh_iris1 = "audio/sfx/Iris_laught.flac"
define sfx_laugh_iris2 = "audio/sfx/Iris_ridicule.wav"
define sfx_laugh_female1 = "audio/sfx/laugh_female1.wav"
define sfx_laugh_female2 = "audio/sfx/laugh_female2.wav"
define sfx_laugh_female3 = "audio/sfx/laugh_female3.wav"
define sfx_loop_piano = "audio/sfx/loop_piano.ogg"
define sfx_heart_beat_neutral = "audio/sfx/heart_beat_neutral.ogg"
define sfx_heart_beat1 = "audio/sfx/heart_beat1.wav"
define sfx_heart_beat2 = "audio/sfx/heart_beat2.ogg"
define sfx_heart_beat_slow = "audio/sfx/heart_beat_slow.wav"
define sfx_heart_beat_fast = "audio/sfx/heart_beat_fast.wav"
define sfx_hiss = "audio/sfx/hiss.wav"
define sfx_hiss_long = "audio/sfx/hiss_long.wav"
define sfx_hiss_electrisity = "audio/sfx/hit_on_panel_dvigatel.aac"
define sfx_hiss_with_voice1 = "audio/sfx/hiss_with_voice1.wav"
define sfx_hit = "audio/sfx/hit.ogg"
define sfx_kitchen = "audio/sfx/kitchen.wav"
define sfx_kitchen_table = "audio/sfx/kitchen_table.ogg"
define sfx_metal_door = "audio/sfx/metal_door.ogg"
define sfx_metal_knock = "audio/sfx/metal_knock.ogg"
define sfx_metal_skrip = "audio/sfx/metal_skrip.ogg"
define sfx_metal_hits_grinding = "audio/sfx/metal_hits_grinding.ogg"
define sfx_morse = "audio/sfx/morse.ogg"
define sfx_noise = "audio/sfx/noise.ogg"
define sfx_noise_banging = "audio/sfx/noise_banging.wav"
define sfx_pisk_one = "audio/sfx/pisk.wav"
define sfx_pisk = "audio/sfx/pisk.ogg"
define sfx_pisk_cicle = "audio/sfx/pisk_cicle.ogg"
define sfx_pisk_radist = "audio/sfx/pisk_radist.ogg"
define sfx_push_button = "audio/sfx/push_button.ogg"
define sfx_power_down = "audio/sfx/power_down.ogg"
define sfx_power_up = "audio/sfx/power_up.ogg"
define sfx_putting_down_plate = "audio/sfx/putting_down_plate.ogg"
define sfx_radist_hit_table = "audio/sfx/radist_hit_table.ogg"
define sfx_run_metal_floor = "audio/sfx/run_metal_floor.ogg"
define sfx_shlepok = "audio/sfx/shlepok.ogg"
define sfx_scream_women_ah = "audio/sfx/scream_women_ah.ogg"
define sfx_shooting = "audio/sfx/shooting.ogg"
define sfx_silent_alarm = "audio/sfx/silent_alarm.ogg"
define sfx_steps = "audio/sfx/steps.ogg"
define sfx_steps_short = "audio/sfx/steps_short.wav"
define sfx_steps_two = "audio/sfx/steps_two.wav"
define sfx_steps_fast = "audio/sfx/steps_fast.ogg"
define sfx_strem_steps = "audio/sfx/strem_steps.ogg"
define sfx_strem_steps_david = "audio/sfx/strem_steps_david.ogg"
define sfx_steps_slow = "audio/sfx/steps_slow.ogg"
define sfx_stun = "audio/sfx/stun.wav"
define sfx_talk = "audio/sfx/talk.ogg"
define sfx_talk_people = "audio/sfx/talk_people.wav"
define sfx_ventel = "audio/sfx/ventel.ogg"
define sfx_ventel_noise = "audio/sfx/ventel_noise.ogg"
define sfx_ventel2 = "audio/sfx/ventel2.ogg"
define sfx_water_splash = "audio/sfx/water_splash.ogg"
define sfx_whistling = "audio/sfx/whistling.wav"

# Интерфейс
define sfx_ui_achieve = "audio/sfx/UI 01 Achive.ogg"
define sfx_ui_click = "audio/sfx/UI 02 Click.ogg"
define sfx_ui_over = "audio/sfx/UI 03 Over.ogg"

# каналы
init python:
    renpy.music.register_channel("ui", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("sfx", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("sfx2", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)
    renpy.music.register_channel("sfx3", mixer="sfx", loop=False, stop_on_mute=True, tight=True, buffer_queue=True)